name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # IMPORTANT for full history

      - name: Mirror repo
        run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror@github.com"

          git remote add mirror https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/balap-wq/news-app.git

          git push --mirror mirror