name: Mirror to Personal Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Token
        run: |
          if [ -z "${{ secrets.MIRROR_ACCESS_TOKEN }}" ]; then
            echo "❌ TOKEN IS EMPTY - Secret not found!"
          else
            echo "✅ TOKEN EXISTS thats good!"
          fi

      - name: Push to mirror
        env:
          GH_TOKEN: ${{ secrets.MIRROR_ACCESS_TOKEN }}
        run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror@github.com"
          git remote add mirror https://$GH_TOKEN@github.com/balap-wq/news-app.git
          git push mirror --all
          git push mirror --tags