name: Mirror to Personal Repo

on:
  push:
    branches:
      - main
  workflow_dispatch: # 👈 add this line

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror@github.com"

          git push https://x-access-token:$TOKEN@github.com/balap-wq/news-app.git --all
          git push https://x-access-token:$TOKEN@github.com/balap-wq/news-app.git --tags
